In [22]:
import numpy as np

In [23]:
def df_w(W):
    """
    Thực hiện tính gradient của dw1 và dw2
    Arguments:
    W -- np.array [w1, w2]
    Returns:
    dW -- np.array [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    """
    w1, w2 = W
    dW = np.array([0.2 * w1, 4 * w2])
    return dW

### Exercise 1

In [24]:
def sgd(W, dW, lr):
    """
    Thực hiện thuật tóa Gradient Descent để update w1 và w2
    Arguments:
    W -- np.array: [w1, w2]
    dW -- np.array: [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    lr -- float: learning rate
    Returns:
    W -- np.array: [w1, w2] w1 và w2 sau khi đã update
    """

    W = W - lr * dW
    return W

In [25]:
def train_p1(optimizer, lr, epochs):
    """
    Thực hiện tìm điểm minimum của function (1) dựa vào thuật toán
    được truyền vào từ optimizer
    Arguments:
    optimize : function thực hiện thuật toán optimization cụ thể
    lr -- float: learning rate
    epoch -- int: số lượng lần (epoch) lặp để tìm điểm minimum
    Returns:
    results -- list: list các cặp điểm [w1, w2] sau mỗi epoch (mỗi lần cập nhật)
    """

    # initial point
    W = np.array([-5, -2], dtype=np.float32)
    # list of results
    results = [W]

    for _ in range(epochs):
        dW = df_w(W)  # Tìm gradient dW
        W = optimizer(W, dW, lr)  # Cập nhật W bằng thuật toán optimizer
        results.append(W.copy())  # Lưu kết quả vào list results

    return results

In [26]:
train_p1(sgd, lr=0.4, epochs=30)

[array([-5., -2.], dtype=float32),
 array([-4.6,  1.2]),
 array([-4.232, -0.72 ]),
 array([-3.89344,  0.432  ]),
 array([-3.5819648, -0.2592   ]),
 array([-3.29540762,  0.15552   ]),
 array([-3.03177501, -0.093312  ]),
 array([-2.78923301,  0.0559872 ]),
 array([-2.56609437, -0.03359232]),
 array([-2.36080682,  0.02015539]),
 array([-2.17194227, -0.01209324]),
 array([-1.99818689,  0.00725594]),
 array([-1.83833194, -0.00435356]),
 array([-1.69126538,  0.00261214]),
 array([-1.55596415, -0.00156728]),
 array([-1.43148702e+00,  9.40369969e-04]),
 array([-1.31696806e+00, -5.64221981e-04]),
 array([-1.21161061e+00,  3.38533189e-04]),
 array([-1.11468176e+00, -2.03119913e-04]),
 array([-1.02550722e+00,  1.21871948e-04]),
 array([-9.43466646e-01, -7.31231688e-05]),
 array([-8.67989314e-01,  4.38739013e-05]),
 array([-7.98550169e-01, -2.63243408e-05]),
 array([-7.34666155e-01,  1.57946045e-05]),
 array([-6.75892863e-01, -9.47676268e-06]),
 array([-6.21821434e-01,  5.68605761e-06]),
 array([-

### Exercise 2

In [27]:
def sgd_momentum(W, dW, lr, V, beta):
    """
    Thực hiện thuật toán Gradient Descent + Momentum để update w1 và w2
    Arguments:
    W -- np.array: [w1, w2]
    dW -- np.array: [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    lr -- float: learning rate
    V -- np.array: [v1, v2] Exponentially weighted averages gradients
    beta -- float: hệ số long-range average
    Returns:
    W -- np.array: [w1, w2] w1 và w2 sau khi đã update
    V -- np.array: [v1, v2] Exponentially weighted averages gradients sau khi đã cập nhật
    """
    # Tính vận tốc mới V
    V = beta * V + (1 - beta) * dW

    # Cập nhật trọng số W
    W = W - lr * V

    return W, V

In [28]:
def train_p2(optimizer, lr, epochs):
    """
    Thực hiện tìm điểm minimum của function (1) dựa vào thuật toán
    được truyền vào từ optimizer
    Arguments:
    optimize : function thực hiện thuật toán optimization cụ thể
    lr -- float: learning rate
    epochs -- int: số lượng lần (epoch) lặp để tìm điểm minimum
    Returns:
    results -- list: list các cặp điểm [w1, w2] sau mỗi epoch (mỗi lần cập nhật)
    """
    # Khởi tạo trọng số và vận tốc
    W = np.array([-5, -2], dtype=np.float32)
    V = np.array([0, 0], dtype=np.float32)
    results = [W]

    for epoch in range(epochs):
        dW = df_w(W)

        W, V = optimizer(W, dW, lr, V, beta=0.5)

        results.append(W)

    return results


In [29]:
train_p2(sgd_momentum, lr=0.6, epochs=30)

[array([-5., -2.], dtype=float32),
 array([-4.7,  0.4]),
 array([-4.268,  1.12 ]),
 array([-3.79592,  0.136  ]),
 array([-3.3321248, -0.5192   ]),
 array([-2.90029971, -0.22376   ]),
 array([-2.51036919,  0.192472  ]),
 array([-2.16478177,  0.1696216 ]),
 array([-1.86210116, -0.04534952]),
 array([-1.59903478, -0.09841566]),
 array([-1.37155951, -0.00684994]),
 array([-1.1755283 ,  0.04715285]),
 array([-1.006981  ,  0.01757082]),
 array([-0.86228849, -0.01830518]),
 array([-0.73820492, -0.01427696]),
 array([-0.63187084,  0.0048695 ]),
 array([-0.54079155,  0.00859933]),
 array([-4.62804416e-01,  1.45050014e-04]),
 array([-0.39604258, -0.00425615]),
 array([-0.33889911, -0.00134937]),
 array([-0.28999343,  0.00172326]),
 array([-0.24814098,  0.00119166]),
 array([-0.2123263 , -0.00050413]),
 array([-0.18167938, -0.00074707]),
 array([-1.55455157e-01,  2.79448010e-05]),
 array([-0.13301574,  0.00038192]),
 array([-1.13815082e-01,  1.00603444e-04]),
 array([-0.09738585, -0.00016078]),
 

### Exercise 3

In [30]:
def RMSProp(W, dW, lr, S, gamma):
    """
    Thực hiện thuật toán RMSProp để cập nhật w1 và w2
    Arguments:
    W -- np.array: [w1, w2]
    dW -- np.array: [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    lr -- float: learning rate (α)
    S -- np.array: [s1, s2] Exponentially weighted averages bình phương gradients
    gamma -- float: hệ số long-range average (γ)
    Returns:
    W -- np.array: [w1, w2] sau khi đã update
    S -- np.array: [s1, s2] sau khi đã update
    """
    epsilon = 1e-6

    S = gamma * S + (1 - gamma) * dW**2

    W = W - lr * dW / (np.sqrt(S) + epsilon)

    return W, S

In [31]:
def train_p3(optimizer, lr, epochs, gamma):
    """
    Thực hiện tìm điểm minimum của function (1) dựa vào thuật toán
    được truyền vào từ optimizer
    Arguments:
    optimizer : function thực hiện thuật toán optimization cụ thể
    lr -- float: learning rate (α)
    epochs -- int: số lượng lần (epoch) lặp để tìm điểm minimum
    gamma -- float: hệ số long-range average trong thuật toán RMSProp (γ)
    Returns:
    results -- list: list các cặp điểm [w1, w2] sau mỗi epoch (mỗi lần cập nhật)
    """
    # Initial points
    W = np.array([-5, -2], dtype=np.float32)
    S = np.array([0, 0], dtype=np.float32)
    results = [W]

    for epoch in range(epochs):
         dW = df_w(W)
         W, S = optimizer(W, dW, lr, S, gamma)
         results.append(W)

    return results

In [32]:
train_p3(RMSProp, lr=0.3, epochs=30, gamma=0.9)

[array([-5., -2.], dtype=float32),
 array([-4.0513197 , -1.05131708]),
 array([-3.43519553, -0.59152376]),
 array([-2.95893489, -0.3294397 ]),
 array([-2.56546089, -0.17756504]),
 array([-2.22920358, -0.09163272]),
 array([-1.93626564, -0.04494508]),
 array([-1.67817504, -0.02081429]),
 array([-1.44934809, -0.00903562]),
 array([-1.24588029, -0.00364592]),
 array([-1.06490135, -0.00135352]),
 array([-9.04200650e-01, -4.56447225e-04]),
 array([-7.61994932e-01, -1.37563947e-04]),
 array([-6.36776983e-01, -3.62604278e-05]),
 array([-5.27213771e-01, -8.11346375e-06]),
 array([-4.32077091e-01, -1.47475425e-06]),
 array([-3.50197152e-01, -2.02787524e-07]),
 array([-2.80433359e-01, -1.84235524e-08]),
 array([-2.21658617e-01, -7.67771777e-10]),
 array([-1.72754375e-01,  7.80432778e-12]),
 array([-1.32614084e-01, -5.05777072e-13]),
 array([-1.00152823e-01,  6.19098174e-14]),
 array([-7.43209130e-02, -1.13368674e-14]),
 array([-5.41193712e-02,  2.80153177e-15]),
 array([-3.86152607e-02, -8.81296

### Exercise 4

In [33]:
import numpy as np

def Adam(W, dW, lr, V, S, beta1, beta2, t):
    """
    Thực hiện thuật toán Adam để cập nhật w1 và w2.

    Arguments:
    W -- np.array: [w1, w2]
    dW -- np.array: [dw1, dw2], array chứa giá trị đạo hàm theo w1 và w2
    lr -- float: learning rate
    V -- np.array: [v1, v2] Exponentially weighted averages gradients
    S -- np.array: [s1, s2] Exponentially weighted averages bình phương gradients
    beta1 -- float: hệ số long-range average cho V
    beta2 -- float: hệ số long-range average cho S
    t -- int: số epoch hiện tại (từ 1 trở đi)

    Returns:
    W -- np.array: [w1, w2] w1 và w2 sau khi đã update
    V -- np.array: [v1, v2] Exponentially weighted averages gradients sau khi đã cập nhật
    S -- np.array: [s1, s2] Exponentially weighted averages bình phương gradients sau khi đã cập nhật
    """
    epsilon = 1e-6

    V = beta1 * V + (1 - beta1) * dW
    S = beta2 * S + (1 - beta2) * (dW ** 2)

    V_hat = V / (1 - beta1 ** t)
    S_hat = S / (1 - beta2 ** t)

    W = W - lr * V_hat / (np.sqrt(S_hat) + epsilon)

    return W, V, S

In [34]:
def train_p4(optimizer, lr, epochs, beta1=0.9, beta2=0.999):
    """
    Thực hiện tìm điểm minimum của function (1) với Adam.

    Arguments:
    optimizer -- function thực hiện thuật toán optimization (Adam)
    lr -- float: learning rate
    epochs -- int: số lượng lần (epoch) lặp để tìm điểm minimum
    beta1 -- float: hệ số long-range average cho V (mặc định là 0.9)
    beta2 -- float: hệ số long-range average cho S (mặc định là 0.999)

    Returns:
    results -- list: list các cặp điểm [w1, w2] sau mỗi epoch (mỗi lần cập nhật)
    """
    # Khởi tạo các tham số
    W = np.array([-5, -2], dtype=np.float32)  # Khởi tạo w1 và w2
    V = np.array([0, 0], dtype=np.float32)  # Khởi tạo v1 và v2
    S = np.array([0, 0], dtype=np.float32)  # Khởi tạo s1 và s2
    results = [W]

    for t in range(1, epochs + 1):
        dW = df_w(W)
        W, V, S = optimizer(W, dW, lr, V, S, beta1, beta2, t)
        results.append(W)

    return results

In [35]:
train_p4(Adam, lr=0.2, epochs=30)

[array([-5., -2.], dtype=float32),
 array([-4.8000002 , -1.80000002]),
 array([-4.60025478, -1.60082451]),
 array([-4.40094848, -1.40317262]),
 array([-4.20227764, -1.20787822]),
 array([-4.00445033, -1.01592745]),
 array([-3.80768638, -0.82847307]),
 array([-3.61221732, -0.64684159]),
 array([-3.41828623, -0.47252765]),
 array([-3.22614739, -0.30716934]),
 array([-3.03606592, -0.15249855]),
 array([-2.84831706, -0.01026326]),
 array([-2.66318543,  0.11787552]),
 array([-2.480964  ,  0.23046161]),
 array([-2.30195279,  0.3263587 ]),
 array([-2.12645742,  0.40484195]),
 array([-1.95478732,  0.46564961]),
 array([-1.7872537 ,  0.50898799]),
 array([-1.62416726,  0.53549442]),
 array([-1.46583566,  0.54617144]),
 array([-1.31256067,  0.54230812]),
 array([-1.16463526,  0.52540206]),
 array([-1.02234036,  0.4970906 ]),
 array([-0.88594163,  0.4590951 ]),
 array([-0.75568617,  0.41317781]),
 array([-0.63179919,  0.3611089 ]),
 array([-0.51448089,  0.30464048]),
 array([-0.40390346,  0.24548